// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBDR4cmF7XDdjKBkJqNJHszGA5kEQGSKc',
    appId: '1:615351642956:web:beca2d27c20396d6fabde9',
    messagingSenderId: '615351642956',
    projectId: 'hackenza-e2886',
    authDomain: 'hackenza-e2886.firebaseapp.com',
    storageBucket: 'hackenza-e2886.appspot.com',
    measurementId: 'G-BYTF97BLGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNfl-ZOv2LLyulNIT4cAunsXBQpyVG0ro',
    appId: '1:615351642956:android:ebbf9031636f888efabde9',
    messagingSenderId: '615351642956',
    projectId: 'hackenza-e2886',
    storageBucket: 'hackenza-e2886.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArGGTetCYZ9hIZyWTyIGzZKi6p9pnrgCY',
    appId: '1:615351642956:ios:cd33fe4ce1a57087fabde9',
    messagingSenderId: '615351642956',
    projectId: 'hackenza-e2886',
    storageBucket: 'hackenza-e2886.appspot.com',
    iosBundleId: 'com.example.sopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArGGTetCYZ9hIZyWTyIGzZKi6p9pnrgCY',
    appId: '1:615351642956:ios:51d556ae2ded2966fabde9',
    messagingSenderId: '615351642956',
    projectId: 'hackenza-e2886',
    storageBucket: 'hackenza-e2886.appspot.com',
    iosBundleId: 'com.example.sopapp.RunnerTests',
  );
}
